blog/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.urls import views as auth_views
from blog.views import PostDetail,PostCreate,PostList,PostUpdate,PostDelete,Dashboard,PostCategory


app_name='blog'

urlpatterns = [
    # path('',Home.as_view(),name='home'),
    path('login/',auth_views.LoginView.as_view(template_name='blog/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('',PostList.as_view(),name='home'),
    path('<int:pk>/',PostDetail.as_view(),name='detail'),
    path('category/<int:pk>/',PostCategory.as_view(),name='category'),
    path('create/',PostCreate.as_view(),name='create'),
    path('<int:pk>/edit/',PostUpdate.as_view(),name='edit'),
    path('<int:pk>/delete/',PostDelete.as_view(),name='delete'),
    path('dashboard/',Dashboard.as_view(),name='dashboard'),
]

classbasedviews/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blog.urls'),name='blog'),
    path('admin/', admin.site.urls),
] 

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.template.defaultfilters import slugify


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    creator = models.ForeignKey(User,on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('post_by_category', args=[self.name])


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    view_count = models.PositiveIntegerField(default=0)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', args=[self.pk])


class Comment(models.Model):
    content = models.TextField()
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    timestamp= models.DateTimeField(auto_now_add=True)
    updated= models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.content)
    

blog/forms.py
from django.forms import ModelForm
from blog.models import Post,Comment


class PostForm(ModelForm):
    class Meta:
        model =Post
        fields =['title','content','author','category']

class CommentForm(ModelForm):
    class Meta:
        model =Comment
        fields =['content',]

blog/views.py
from django.shortcuts import render
from django.views.generic import View,ListView,DetailView,CreateView,UpdateView,DeleteView,FormView
from django.views.generic.detail import SingleObjectMixin
from django.shortcuts import get_object_or_404,redirect,reverse
from django.urls import reverse_lazy
import requests
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from blog.models import Post,Comment,Category
from blog.forms import PostForm,CommentForm


#our custom mixin
class PageContentMixin(object):
    page_title=None

    def get_context_data(self,**kwargs):
        context=super().get_context_data()
        context['page_title'] =self.page_title
        return context


class PostList(PageContentMixin,ListView):
    model =Post
    template_name ='blog/home.html'
    context_object_name='posts'
    ordering ='-pub_date'
    paginate_by =3
    page_title='Goldie\'s Home'


# class PostDisplay(DetailView):
#     #main mixin :SingleObjectMixin 
#     model = Post
#     context_object_name='post'
#     pk_url_kwarg='pk'
#     template_name ='blog/post_detail.html'

#     #Returns the object the view is displaying. 
#     def get_object(self):
#         post = super().get_object() #the current post
#         post.view_count = post.view_count +1 
#         post.save()
#         return post

#     def get_context_data(self,*args,**kwargs):
#         """Insert the single object into the context dict."""
#         context = super().get_context_data(**kwargs)#the current context
#         context['comments'] =Comment.objects.filter(post= self.get_object())#get the current post
#         context['form']=CommentForm
#         return context

class PostDisplay(SingleObjectMixin,View):

    model = Post

    def get(self,request,*args,**kwargs):
        self.object = self.get_object()
        self.object.view_count = self.object.view_count +1 
        self.object.save()
        post = self.get_context_data(object=self.object)
        return render(request,'blog/post_detail.html',post)

    def get_context_data(self,*args,**kwargs):
        """Insert the single object into the context dict."""
        context = super().get_context_data(**kwargs)#the current context
        context['comments'] =Comment.objects.filter(post= self.get_object())#get the current post
        context['form']=CommentForm
        return context
      
            
class PostComment(FormView):
    form_class = CommentForm
    template_name='blog/post_detail.html'

    def form_valid(self,form):
        form.instance.author = self.request.user
        post = Post.objects.get(pk=self.kwargs['pk'])
        form.instance.post= post
        form.save()
        return super(PostComment,self).form_valid(form)

    def get_success_url(self):
        return reverse('blog:detail',kwargs={'pk':self.kwargs['pk']})    


class PostDetail(PageContentMixin,View):
    page_title='detail'
    def get(self,request,*args,**kwargs):
        view = PostDisplay.as_view()
        return view(request,*args,**kwargs) 

    def post(self,request,*args,**kwargs):
        view = PostComment.as_view()
        return view(request,*args,**kwargs) 


class PostCreate(PageContentMixin,CreateView):
    #ModelFormMixin is the main one
    model = Post
    fields = ['title','category','content']
    page_title='Create new post'

    def form_valid(self,form):
        """If the form is valid, save the associated model."""
        form.instance.author =self.request.user
        form.save()
        return super(PostCreate,self).form_valid(form)


class PostUpdate(PageContentMixin,UpdateView):
    model =Post
    fields =['title','category','content']
    page_title='update'

class PostDelete(PageContentMixin,DeleteView):
    model =Post
    success_url= reverse_lazy('blog:home')#wait till url is available ,since only after deletion we want to redirect
    context_object_name='post'
    template_name='blog/post_confirm_delete.html'
    page_title='delete post'



#inheriting a class and overriding its properties
@method_decorator(login_required,name='dispatch')#lookout for get,put,post,delete
class Dashboard(PageContentMixin,View):
    page_title='dashboard'
    def get(self, request,*args,**kwargs):
        view = PostList.as_view(
            template_name='blog/admin_page.html',
            paginate_by=4 
            )
        return view(request,*args,**kwargs)       


class PostCategory(PageContentMixin,ListView):
    model =Post
    template_name='blog/post_category.html'
    context_object_name='posts'
    paginate_by =3
    page_title='category'

    def get_queryset(self):
        self.category = get_object_or_404(Category,pk=self.kwargs['pk'])
        return Post.objects.filter(category=self.category)

    def get_context_data(self,**kwargs):
        context = super().get_context_data()
        context['category'] = self.category
        return context     


# class Home(View):
#     def get(self,request,*args,**kwargs):
#         posts = Post.objects.all()
#         return render(request,'blog/home.html',{'posts':posts})


# class PostDetail(View):
#     #similar to detail of function based view 
#     def get(self,request,pk,*args,**kwargs):
#         #class based views fetches by default by slug,or pk
#         post = get_object_or_404(Post,pk=pk)
#         return render(request,'blog/post_detail.html',{'post':post})


# class PostCreate(View):
    
#     def get(self,request,*args,**kwargs):
#         form =PostForm
#         return render(request,'blog/post_form.html',{'form':form})

#     def post(self,request,*args,**kwargs):
#         form=PostForm(request.POST)  
#         if form.is_valid:
#             form.save()
#             return redirect('blog:home') 
#         return render(request,'blog/post_form.html',{'form':form}) 

blog/templates/blog/admin_page.html
{% extends 'blog/base.html' %}

{% block breadcrumb %}{{ block.super }} > Admin{% endblock %}

{% block content %}

    <div class="blog-table">
        <h2><a href="{%url 'blog:create' %}">&#9997 New Post</a></h2>
        <table>
            <tr>
                <th>Title</th>
                <th colspan="2">Actions</th>
            </tr>
            {%for post in posts%}
            <tr>
                <td>{{post.title}}</td>
                <td><a href="{%url 'blog:edit' post.pk%}">&#9998 Edit</a></td>
                <td><a href="{%url 'blog:delete' post.pk%}">&#128465 Delete</a></td>
            </tr>
            {%endfor%}
         
        </table>
                    
    </div>

    {% include 'blog/pagination_links.html' %}

{% endblock %}

blog/templates/blog/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Bloggest{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'blog/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
</head>
<body>
    
    <nav>
        <h2><a href="{%url 'blog:home'%}">&#x1f451 Bloggest</a></h2>
        {% if user.is_authenticated %}
            <p><a href="{%url 'blog:logout'%}">&#128274 Logout</a></p>
        {% else %}
            <p><a href="{%url 'blog:login'%}">&#128275 Login</a></p>
        {% endif %}
    </nav>

    <section class="content-wrapper">
        <div class="breadcrumb">
            <p>{% block breadcrumb %}<a href="{%url 'blog:home'%}">Home</a>{% endblock %}</p>
        </div>
        
        {% block content %}

        {% endblock %}
    </section>

</body>
</html>

blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block title %}
{{page_title}}
{% endblock title %}

{% block content %}

    {% for post in posts%}
    <div class="blog-item">
        <h2><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
        <div class="info">
            By <span><a href="#">{{post.author}}</a></span> | In <span><a href="{%url 'blog:category' post.category.pk%}">{{post.category}}</a></span> | On <span>{{post.pub_date}}</span> | &#x1f441 <span>{{post.view_count}} Views</span> 
        </div>
        <p>{{post.content|truncatewords:35}}</p>
    </div>
    {%endfor%}


    {% include 'blog/pagination_links.html' %}

{% endblock %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}

{% block breadcrumb %}{% endblock %}

{% block content %}

    <div class="form login-form">
        <form method="POST" action="." novalidate>
            {%csrf_token%}
            {{form.as_p}}
           
            
            <p><input type="submit" value="Login"></p> 
        </form>
    </div>

{% endblock %}

blog/templates/blog/pagination_links.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

blog/templates/blog/post_category.html
{% extends 'blog/base.html' %}

{% block content %}

    <div><h3>{{category.name}} category</h3></div>
    
    {% for post in posts%}
    <div class="blog-item">
        <h2><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
        <div class="info">
            By <span><a href="#">{{post.author}}</a></span> | In <span><a href="#">{{post.category}}</a></span> | On <span>{{post.pub_date}}</span> | &#x1f441 <span>{{post.view_count}} Views</span> 
        </div>
        <p>{{post.content|truncatewords:35}}</p>
    </div>
    {%endfor%}


    {% include 'blog/pagination_links.html' %}

{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block breadcrumb %}{{ block.super }} > Admin page > Confirm delete{% endblock %}

{% block content %}
    <div class="form">
        <h2>Are you sure you want to delete the "<b>{{ post.title }}</b>" task?</h2>
        <form action="" method="post" novalidate>
            {% csrf_token %}
            <input type="submit" value="Yes">
        </form>
    </div>
    
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% load static %}

{% block breadcrumb %}{{ block.super }} > {{post.title}}{% endblock %}

{% block content %}

<div class="blog-item">
    <h2><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
    <div class="info">
        By <span><a href="#">{{post.author}}</a></span> | In <span><a href="#">{{post.category}}</a></span> | On <span>{{post.pub_date}}</span> | &#x1f441 <span>{{post.view_count}} Views</span> 
    </div>
    <p>{{post.content}}</p>
</div>

    <div class="form">
        <form method="POST" action='.'>
            {%csrf_token%}
            {{form.as_p}}
         
            
            <p><input type="submit" value="Submit"></p> 
        </form>
    </div>


    <div class="comments-list">
        {%for cmt in comments%}
        <div class="comment">
            <img src="{% static 'blog/images/avatar.png' %}" alt="avatar">
            <div class="info">
                <p>{{cmt.author}}<span> . {{cmt.timestamp}}</span></p>
                <p>{{cmt.content}}</p>
            </div>   
        </div>
        {% endfor %}
    </div>

{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block breadcrumb %}{{ block.super }} > Admin page > New Post{% endblock %}

{% block content %}

    <div class="form">
        <form method="POST" action='.'>
            {%csrf_token%}
            {{form.as_p}}
         
            
            <p><input type="submit" value="Submit"></p> 
        </form>
    </div>

{% endblock %}